import Link from "next/link";
import React from "react";

const PrivacyPolicy = () => {
  return (
    <section className="w-full py-20 flex flex-col items-center justify-start gap-4">
      <h1>Privacy Policy</h1>
      <p>Last updated: May 04, 2023</p>
      <p>
        This Privacy Policy describes Our policies and procedures on the
        collection, use and disclosure of Your information when You use the
        Service and tells You about Your privacy rights and how the law protects
        You.
      </p>
      <p>
        We use Your Personal data to provide and improve the Service. By using
        the Service, You agree to the collection and use of information in
        accordance with this Privacy Policy.
      </p>
      <strong className="text-3xl">Interpretation and Definitions</strong>
      <strong className="text-2xl">Interpretation</strong>
      <p>
        The words of which the initial letter is capitalized have meanings
        defined under the following conditions. The following definitions shall
        have the same meaning regardless of whether they appear in singular or
        in plural.
      </p>
      <strong className="text-2xl">Definitions</strong>
      <p>For the purposes of this Privacy Policy:</p>
      <ul>
        <li>
          <p>
            <strong>Account</strong> means a unique account created for You to
            access our Service or parts of our Service.
          </p>
        </li>
        <li>
          <p>
            <strong>Affiliate</strong> means an entity that controls, is
            controlled by or is under common control with a party, where
            &quot;control&quot; means ownership of 50% or more of the shares,
            equity interest or other securities entitled to vote for election of
            directors or other managing authority.
          </p>
        </li>
        <li>
          <p>
            <strong>Application</strong> refers to Spotloc, the software program
            provided by the Company.
          </p>
        </li>
        <li>
          <p>
            <strong>Company</strong> (referred to as either &quot;the
            Company&quot;, &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot; in
            this Agreement) refers to Spotloc.
          </p>
        </li>
        <li>
          <p>
            <strong>Cookies</strong> are small files that are placed on Your
            computer, mobile device or any other device by a website, containing
            the details of Your browsing history on that website among its many
            uses.
          </p>
        </li>
        <li>
          <p>
            <strong>Country</strong> refers to: Latvia
          </p>
        </li>
        <li>
          <p>
            <strong>Device</strong> means any device that can access the Service
            such as a computer, a cellphone or a digital tablet.
          </p>
        </li>
        <li>
          <p>
            <strong>Personal Data</strong> is any information that relates to an
            identified or identifiable individual.
          </p>
        </li>
        <li>
          <p>
            <strong>Service</strong> refers to the Application or the Website or
            both.
          </p>
        </li>
        <li>
          <p>
            <strong>Service Provider</strong> means any natural or legal person
            who processes the data on behalf of the Company. It refers to
            third-party companies or individuals employed by the Company to
            facilitate the Service, to provide the Service on behalf of the
            Company, to perform services related to the Service or to assist the
            Company in analyzing how the Service is used.
          </p>
        </li>
        <li>
          <p>
            <strong>Usage Data</strong> refers to data collected automatically,
            either generated by the use of the Service or from the Service
            infrastructure itself (for example, the duration of a page visit).
          </p>
        </li>
        <li>
          <p>
            <strong>Website</strong> refers to Spotloc, accessible from
            <a href="https://www.spotloc.lv" rel="noreferrer" target="_blank">
              https://www.spotloc.lv
            </a>
          </p>
        </li>
        <li>
          <p>
            <strong>You</strong> means the individual accessing or using the
            Service, or the company, or other legal entity on behalf of which
            such individual is accessing or using the Service, as applicable.
          </p>
        </li>
      </ul>
      <strong className="text-3xl">
        Collecting and Using Your Personal Data
      </strong>
      <strong className="text-2xl">Types of Data Collected</strong>
      <h3>Personal Data</h3>
      <p>
        While using Our Service, We may ask You to provide Us with certain
        personally identifiable information that can be used to contact or
        identify You. Personally identifiable information may include, but is
        not limited to:
      </p>
      <ul>
        <li>
          <p>Email address</p>
        </li>
        <li>
          <p>First name and last name</p>
        </li>
        <li>
          <p>Phone number</p>
        </li>
        <li>
          <p>Usage Data</p>
        </li>
      </ul>
      <h3>Usage Data</h3>
      <p>Usage Data is collected automatically when using the Service.</p>
      <p>
        Usage Data may include information such as Your Device&apos;s Internet
        Protocol address (e.g. IP address), browser type, browser version, the
        pages of our Service that You visit, the time and date of Your visit,
        the time spent on those pages, unique device identifiers and other
        diagnostic data.
      </p>
      <p>
        When You access the Service by or through a mobile device, We may
        collect certain information automatically, including, but not limited
        to, the type of mobile device You use, Your mobile device unique ID, the
        IP address of Your mobile device, Your mobile operating system, the type
        of mobile Internet browser You use, unique device identifiers and other
        diagnostic data.
      </p>
      <p>
        We may also collect information that Your browser sends whenever You
        visit our Service or when You access the Service by or through a mobile
        device.
      </p>
      <h3>Tracking Technologies and Cookies</h3>
      <p>
        We use Cookies and similar tracking technologies to track the activity
        on Our Service and store certain information. Tracking technologies used
        are beacons, tags, and scripts to collect and track information and to
        improve and analyze Our Service. The technologies We use may include:
      </p>
      <ul>
        <li>
          <strong>Cookies or Browser Cookies.</strong> A cookie is a small file
          placed on Your Device. You can instruct Your browser to refuse all
          Cookies or to indicate when a Cookie is being sent. However, if You do
          not accept Cookies, You may not be able to use some parts of our
          Service. Unless you have adjusted Your browser setting so that it will
          refuse Cookies, our Service may use Cookies.
        </li>
        <li>
          <strong>Web Beacons.</strong> Certain sections of our Service and our
          emails may contain small electronic files known as web beacons (also
          referred to as clear gifs, pixel tags, and single-pixel gifs) that
          permit the Company, for example, to count users who have visited those
          pages or opened an email and for other related website statistics (for
          example, recording the popularity of a certain section and verifying
          system and server integrity).
        </li>
      </ul>
      <p>
        Cookies can be &quot;Persistent&quot; or &quot;Session&quot; Cookies.
        Persistent Cookies remain on Your personal computer or mobile device
        when You go offline, while Session Cookies are deleted as soon as You
        close Your web browser.
      </p>
      <p>
        We use both Session and Persistent Cookies for the purposes set out
        below:
      </p>
      <ul>
        <li>
          <p>
            <strong>Necessary / Essential Cookies</strong>
          </p>
          <p>Type: Session Cookies</p> <p>Administered by: Us</p>
          <p>
            Purpose: These Cookies are essential to provide You with services
            available through the Website and to enable You to use some of its
            features. They help to authenticate users and prevent fraudulent use
            of user accounts. Without these Cookies, the services that You have
            asked for cannot be provided, and We only use these Cookies to
            provide You with those services.
          </p>
        </li>
        <li>
          <p>
            <strong>Cookies Policy / Notice Acceptance Cookies</strong>
          </p>
          <p>Type: Persistent Cookies</p> <p>Administered by: Us</p>
          <p>
            Purpose: These Cookies identify if users have accepted the use of
            cookies on the Website.
          </p>
        </li>
        <li>
          <p>
            <strong>Functionality Cookies</strong>
          </p>
          <p>Type: Persistent Cookies</p> <p>Administered by: Us</p>
          <p>
            Purpose: These Cookies allow us to remember choices You make when
            You use the Website, such as remembering your login details or
            language preference. The purpose of these Cookies is to provide You
            with a more personal experience and to avoid You having to re-enter
            your preferences every time You use the Website.
          </p>
        </li>
      </ul>
      <p>
        For more information about the cookies we use and your choices regarding
        cookies, please visit our Cookies Policy or the Cookies section of our
        Privacy Policy.
      </p>
      <strong className="text-2xl">Use of Your Personal Data</strong>
      <p>The Company may use Personal Data for the following purposes:</p>
      <ul>
        <li>
          <p>
            <strong>To provide and maintain our Service</strong>, including to
            monitor the usage of our Service.
          </p>
        </li>
        <li>
          <p>
            <strong>To manage Your Account:</strong> to manage Your registration
            as a user of the Service. The Personal Data You provide can give You
            access to different functionalities of the Service that are
            available to You as a registered user.
          </p>
        </li>
        <li>
          <p>
            <strong>For the performance of a contract:</strong> the development,
            compliance and undertaking of the purchase contract for the
            products, items or services You have purchased or of any other
            contract with Us through the Service.
          </p>
        </li>
        <li>
          <p>
            <strong>To contact You:</strong> To contact You by email, telephone
            calls, SMS, or other equivalent forms of electronic communication,
            such as a mobile application&apos;s push notifications regarding
            updates or informative communications related to the
            functionalities, products or contracted services, including the
            security updates, when necessary or reasonable for their
            implementation.
          </p>
        </li>
        <li>
          <p>
            <strong>To provide You</strong> with news, special offers and
            general information about other goods, services and events which we
            offer that are similar to those that you have already purchased or
            enquired about unless You have opted not to receive such
            information.
          </p>
        </li>
        <li>
          <p>
            <strong>To manage Your requests:</strong> To attend and manage Your
            requests to Us.
          </p>
        </li>
        <li>
          <p>
            <strong>For business transfers:</strong> We may use Your information
            to evaluate or conduct a merger, divestiture, restructuring,
            reorganization, dissolution, or other sale or transfer of some or
            all of Our assets, whether as a going concern or as part of
            bankruptcy, liquidation, or similar proceeding, in which Personal
            Data held by Us about our Service users is among the assets
            transferred.
          </p>
        </li>
        <li>
          <p>
            <strong>For other purposes</strong>: We may use Your information for
            other purposes, such as data analysis, identifying usage trends,
            determining the effectiveness of our promotional campaigns and to
            evaluate and improve our Service, products, services, marketing and
            your experience.
          </p>
        </li>
      </ul>
      <p>We may share Your personal information in the following situations:</p>
      <ul>
        <li>
          <strong>With Service Providers:</strong> We may share Your personal
          information with Service Providers to monitor and analyze the use of
          our Service, to contact You.
        </li>
        <li>
          <strong>For business transfers:</strong> We may share or transfer Your
          personal information in connection with, or during negotiations of,
          any merger, sale of Company assets, financing, or acquisition of all
          or a portion of Our business to another company.
        </li>
        <li>
          <strong>With Affiliates:</strong> We may share Your information with
          Our affiliates, in which case we will require those affiliates to
          honor this Privacy Policy. Affiliates include Our parent company and
          any other subsidiaries, joint venture partners or other companies that
          We control or that are under common control with Us.
        </li>
        <li>
          <strong>With business partners:</strong> We may share Your information
          with Our business partners to offer You certain products, services or
          promotions.
        </li>
        <li>
          <strong>With other users:</strong> when You share personal information
          or otherwise interact in the public areas with other users, such
          information may be viewed by all users and may be publicly distributed
          outside.
        </li>
        <li>
          <strong>With Your consent</strong>: We may disclose Your personal
          information for any other purpose with Your consent.
        </li>
      </ul>
      <strong className="text-2xl">Retention of Your Personal Data</strong>
      <p>
        The Company will retain Your Personal Data only for as long as is
        necessary for the purposes set out in this Privacy Policy. We will
        retain and use Your Personal Data to the extent necessary to comply with
        our legal obligations (for example, if we are required to retain your
        data to comply with applicable laws), resolve disputes, and enforce our
        legal agreements and policies.
      </p>
      <p>
        The Company will also retain Usage Data for internal analysis purposes.
        Usage Data is generally retained for a shorter period of time, except
        when this data is used to strengthen the security or to improve the
        functionality of Our Service, or We are legally obligated to retain this
        data for longer time periods.
      </p>
      <strong className="text-2xl">Transfer of Your Personal Data</strong>
      <p>
        Your information, including Personal Data, is processed at the
        Company&apos;s operating offices and in any other places where the
        parties involved in the processing are located. It means that this
        information may be transferred to — and maintained on — computers
        located outside of Your state, province, country or other governmental
        jurisdiction where the data protection laws may differ than those from
        Your jurisdiction.
      </p>
      <p>
        Your consent to this Privacy Policy followed by Your submission of such
        information represents Your agreement to that transfer.
      </p>
      <p>
        The Company will take all steps reasonably necessary to ensure that Your
        data is treated securely and in accordance with this Privacy Policy and
        no transfer of Your Personal Data will take place to an organization or
        a country unless there are adequate controls in place including the
        security of Your data and other personal information.
      </p>
      <strong className="text-2xl">Delete Your Personal Data</strong>
      <p>
        You have the right to delete or request that We assist in deleting the
        Personal Data that We have collected about You.
      </p>
      <p>
        Our Service may give You the ability to delete certain information about
        You from within the Service.
      </p>
      <p>
        You may update, amend, or delete Your information at any time by signing
        in to Your Account, if you have one, and visiting the account settings
        section that allows you to manage Your personal information. You may
        also contact Us to request access to, correct, or delete any personal
        information that You have provided to Us.
      </p>
      <p>
        Please note, however, that We may need to retain certain information
        when we have a legal obligation or lawful basis to do so.
      </p>
      <strong className="text-2xl">Disclosure of Your Personal Data</strong>
      <h3>Business Transactions</h3>
      <p>
        If the Company is involved in a merger, acquisition or asset sale, Your
        Personal Data may be transferred. We will provide notice before Your
        Personal Data is transferred and becomes subject to a different Privacy
        Policy.
      </p>
      <h3>Law enforcement</h3>
      <p>
        Under certain circumstances, the Company may be required to disclose
        Your Personal Data if required to do so by law or in response to valid
        requests by public authorities (e.g. a court or a government agency).
      </p>
      <h3>Other legal requirements</h3>
      <p>
        The Company may disclose Your Personal Data in the good faith belief
        that such action is necessary to:
      </p>
      <ul>
        <li>Comply with a legal obligation</li>
        <li>Protect and defend the rights or property of the Company</li>
        <li>
          Prevent or investigate possible wrongdoing in connection with the
          Service
        </li>
        <li>
          Protect the personal safety of Users of the Service or the public
        </li>
        <li>Protect against legal liability</li>
      </ul>
      <strong className="text-2xl">Security of Your Personal Data</strong>
      <p>
        The security of Your Personal Data is important to Us, but remember that
        no method of transmission over the Internet, or method of electronic
        storage is 100% secure. While We strive to use commercially acceptable
        means to protect Your Personal Data, We cannot guarantee its absolute
        security.
      </p>
      <strong className="text-3xl">Children&apos;s Privacy</strong>
      <p>
        Our Service does not address anyone under the age of 13. We do not
        knowingly collect personally identifiable information from anyone under
        the age of 13. If You are a parent or guardian and You are aware that
        Your child has provided Us with Personal Data, please contact Us. If We
        become aware that We have collected Personal Data from anyone under the
        age of 13 without verification of parental consent, We take steps to
        remove that information from Our servers.
      </p>
      <p>
        If We need to rely on consent as a legal basis for processing Your
        information and Your country requires consent from a parent, We may
        require Your parent&apos;s consent before We collect and use that
        information.
      </p>
      <strong className="text-3xl">Links to Other Websites</strong>
      <p>
        Our Service may contain links to other websites that are not operated by
        Us. If You click on a third party link, You will be directed to that
        third party&apos;s site. We strongly advise You to review the Privacy
        Policy of every site You visit.
      </p>
      <p>
        We have no control over and assume no responsibility for the content,
        privacy policies or practices of any third party sites or services.
      </p>
      <strong className="text-3xl">Changes to this Privacy Policy</strong>
      <p>
        We may update Our Privacy Policy from time to time. We will notify You
        of any changes by posting the new Privacy Policy on this page.
      </p>
      <p>
        We will let You know via email and/or a prominent notice on Our Service,
        prior to the change becoming effective and update the &quot;Last
        updated&quot; date at the top of this Privacy Policy.
      </p>
      <p>
        You are advised to review this Privacy Policy periodically for any
        changes. Changes to this Privacy Policy are effective when they are
        posted on this page.
      </p>
      <strong className="text-3xl">Contact Us</strong>
      <p>
        If you have any questions about this Privacy Policy, You can contact us:
      </p>
      <ul>
        <li>
          <p>By email: info@quickstack.lv</p>
        </li>
        <li>
          <p>By phone number: 26956611</p>
        </li>
      </ul>
    </section>
  );
};

export const PrivacyPolicyLatvian = () => {
  return (
    <section className="w-full py-20 flex flex-col items-center justify-start gap-4">
      <h1>Privātuma politika</h1>
      <p>Pēdējoreiz atjaunināts: 2023. gada 4. maijā</p>
      <p>
        Šajā Privātuma politikā ir aprakstītas mūsu politikas un procedūras Jūsu
        informācijas vākšana, izmantošana un izpaušana, kad izmantojat
        Pakalpojumu un stāsta par jūsu privātuma tiesībām un to, kā to aizsargā
        likums Tu.
      </p>
      <p>
        Mēs izmantojam Jūsu personas datus, lai nodrošinātu un uzlabotu
        Pakalpojumu. Izmantojot Pakalpojumā, Jūs piekrītat informācijas
        apkopošanai un izmantošanai saskaņā ar šo Privātuma politiku.
      </p>
      <strong className="text-3xl">Interpretācija un definīcijas</strong>
      <strong className="text-2xl">Interpretācija</strong>
      <p>
        Vārdiem, kuru sākuma burts ir rakstīts ar lielo burtu, ir nozīme
        definēts saskaņā ar šādiem nosacījumiem. Šādas definīcijas ir viena un
        tā pati nozīme neatkarīgi no tā, vai tie parādās vienskaitlī vai
        daudzskaitlī.
      </p>
      <strong className="text-2xl">Definīcijas</strong>
      <p>Šīs konfidencialitātes politikas mērķiem:</p>
      <ul>
        <li>
          <p>
            <strong>Konts</strong> ir unikāls konts, kas izveidots jums piekļūt
            mūsu Pakalpojumam vai mūsu Pakalpojuma daļām.
          </p>
        </li>
        <li>
          <p>
            <strong>Partneris</strong> ir vienība, kas kontrolē, ir ko kontrolē
            vai ir kopīgā kontrolē ar pusi, kur &quot;kontrole&quot; nozīmē
            īpašumtiesības uz 50% vai vairāk akciju, akciju procenti vai citi
            vērtspapīri, kas ir tiesīgi balsot par ievēlēšanu direktoriem vai
            citai vadošai iestādei.
          </p>
        </li>
        <li>
          <p>
            <strong>Lietojumprogramma</strong> attiecas uz Spotloc,
            programmatūras programmu nodrošina Sabiedrība.
          </p>
        </li>
        <li>
          <p>
            <strong>Uzņēmums</strong> (saukts par &quot; Uzņēmums&quot;,
            &quot;Mēs&quot;, &quot;Mums&quot; vai &quot;Mūsu&quot; iekšā šis
            līgums) attiecas uz Spotloc.
          </p>
        </li>
        <li>
          <p>
            <strong>Sīkfaili</strong> ir mazi faili, kas tiek ievietoti jūsu
            vietnē datoru, mobilo ierīci vai jebkuru citu ierīci, ko nodrošina
            vietne, kas satur detalizētu informāciju par jūsu pārlūkošanas
            vēsturi šajā vietnē starp daudzajām lietojumiem.
          </p>
        </li>
        <li>
          <p>
            <strong>Valsts</strong> attiecas uz Latviju
          </p>
        </li>
        <li>
          <p>
            <strong>Ierīce</strong> ir jebkura ierīce, kas var piekļūt
            Pakalpojumam piemēram, datoru, mobilo tālruni vai digitālo
            planšetdatoru.
          </p>
        </li>
        <li>
          <p>
            <strong>Personas dati</strong> ir jebkura informācija, kas attiecas
            uz identificēta vai identificējama persona.
          </p>
        </li>
        <li>
          <p>
            <strong>Pakalpojums</strong> attiecas uz Lietojumprogrammu vai
            Vietni vai gan.
          </p>
        </li>
        <li>
          <p>
            <strong>Pakalpojumu sniedzējs</strong> ir jebkura fiziska vai
            juridiska persona kas apstrādā datus Sabiedrības vārdā. Tas attiecas
            uz trešās puses uzņēmumi vai privātpersonas, kuras Sabiedrība
            nodarbina atvieglot Pakalpojuma sniegšanu, sniegt Pakalpojumu
            uzņēmuma vārdā Uzņēmums, lai sniegtu ar Pakalpojumu saistītus
            pakalpojumus vai palīdzētu Uzņēmums analizē, kā Pakalpojums tiek
            izmantots.
          </p>
        </li>
        <li>
          <p>
            <strong>Lietošanas dati</strong> attiecas uz datiem, kas savākti
            automātiski, ģenerēts, izmantojot Pakalpojumu, vai no Pakalpojuma
            pati infrastruktūra (piemēram, lapas apmeklējuma ilgums).
          </p>
        </li>
        <li>
          <p>
            <strong>Vietne</strong> attiecas uz Spotloc, kurai var piekļūt no
            <a href="https://www.spotloc.lv" target="_blank" rel="noreferrer">
              https://www.spotloc.lv
            </a>
          </p>
        </li>
        <li>
          <p>
            <strong>Jūs</strong> nozīmē personu, kas piekļūst vai izmanto
            Pakalpojums vai uzņēmums, vai cita juridiska persona, kuras vārdā šī
            persona attiecīgi piekļūst Pakalpojumam vai to izmanto.
          </p>
        </li>
      </ul>
      <strong className="text-3xl">
        Jūsu personas datu vākšana un izmantošana
      </strong>
      <strong className="text-2xl">Apkopoto datu veidi</strong>
      <h3>Personas dati</h3>
      <p>
        Izmantojot mūsu pakalpojumu, mēs varam lūgt jūs sniegt mums noteiktus
        personu identificējoša informācija, ko var izmantot, lai sazinātos vai
        identificēt Jūs. Personu identificējoša informācija n var ietvert, bet
        ir neaprobežojas ar:
      </p>
      <ul>
        <li>
          <p>E-pasta adrese</p>
        </li>
        <li>
          <p>Vārds un uzvārds</p>
        </li>
        <li>
          <p>Tālruņa numurs</p>
        </li>
        <li>
          <p>Lietošanas dati</p>
        </li>
      </ul>
      <h3>Lietošanas dati</h3>
      <p>Lietošanas dati tiek vākti automātiski, kad izmantojat Pakalpojumu.</p>
      <p>
        Lietošanas datos var būt ietverta tāda informācija kā jūsu ierīces
        internets Protokola adrese (piem., IP adrese), pārlūkprogrammas veids,
        pārlūkprogrammas versija, Jūsu apmeklētās mūsu Pakalpojuma lapas, Jūsu
        apmeklējuma laiks un datums, šajās lapās pavadītais laiks, unikālie
        ierīces identifikatori un citi diagnostikas dati.
      </p>
      <p>
        Kad piekļūstat Pakalpojumam, izmantojot mobilo ierīci vai izmantojot
        mobilo ierīci, Mēs varam automātiski apkopo noteiktu informāciju,
        tostarp, bet ne tikai Jūsu izmantotās mobilās ierīces veidam, Jūsu
        mobilās ierīces unikālajam ID, Jūsu mobilās ierīces IP adrese, Jūsu
        mobilā operētājsistēma, veids Jūsu izmantotā mobilā interneta
        pārlūkprogramma, unikālie ierīču identifikatori un citi diagnostikas
        dati.
      </p>
      <p>
        Mēs varam arī apkopot informāciju, ko jūsu pārlūkprogramma nosūta
        ikreiz, kad jūs apmeklējiet mūsu Pakalpojumu vai kad piekļūstat
        Pakalpojumam, izmantojot mobilo tālruni vai izmantojot mobilo tālruni
        ierīci.
      </p>
      <h3>Izsekošanas tehnoloģijas un sīkfaili</h3>
      <p>
        Mēs izmantojam sīkfailus un līdzīgas izsekošanas tehnoloģijas, lai
        izsekotu darbību mūsu Pakalpojumā un uzglabāt noteiktu informāciju.
        Izmantotās izsekošanas tehnoloģijas ir bākas, atzīmes un skripti
        informācijas vākšanai un izsekošanai uzlabot un analizēt mūsu
        pakalpojumu. Mūsu izmantotās tehnoloģijas var ietvert:
      </p>
      <ul>
        <li>
          <strong>Sīkfaili vai pārlūkprogrammas sīkfaili.</strong> Sīkfails ir
          mazs fails ievietots Jūsu ierīcē. Jūs varat uzdot savai
          pārlūkprogrammai atteikt visu Sīkdatnes vai lai norādītu, kad tiek
          nosūtīts sīkfails. Tomēr, ja jūs to darāt nepieņemt sīkfailus,
          iespējams, nevarēsit izmantot dažas mūsu daļas Apkalpošana. Ja vien
          neesat pielāgojis pārlūkprogrammas iestatījumus tā, lai tas būtu
          atteikties no sīkdatnēm, mūsu pakalpojums var izmantot sīkfailus.
        </li>
        <li>
          <strong>Tīmekļa bāksignāli.</strong> Dažas mūsu pakalpojuma sadaļas un
          mūsu e-pastos var būt nelieli elektroniski faili, kas pazīstami kā
          tīmekļa bāksignāli (arī ko dēvē par skaidriem gifiem, pikseļu tagiem
          un viena pikseļa gifiem). ļaut Uzņēmumam, piemēram, uzskaitīt
          lietotājus, kuri tos apmeklējuši lapas vai atvēra e-pastu un citu
          saistīto vietņu statistiku (par piemēram, noteiktas sadaļas
          popularitātes reģistrēšana un pārbaude sistēmas un servera
          integritāte).
        </li>
      </ul>
      <p>
        Sīkfaili var būt &quot;Pastāvīgi&quot; vai &quot;Sesija&quot; Sīkdatnes.
        Pastāvīgās sīkdatnes paliek Jūsu personālajā datorā vai mobilajā ierīcē
        kad pārejat bezsaistē, savukārt sesijas sīkfaili tiek dzēsti, tiklīdz
        jūs aizveriet savu tīmekļa pārlūkprogrammu.
      </p>
      <p>
        Mēs izmantojam gan sesijas, gan pastāvīgos sīkfailus noteiktajiem
        mērķiem zemāk:
      </p>
      <ul>
        <li>
          <p>
            <strong>Nepieciešamie/būtiski sīkfaili</strong>
          </p>
          <p>Veids: sesijas sīkfaili</p> <p>pārvalda: mēs</p>
          <p>
            Mērķis: Šīs sīkdatnes ir būtiskas, lai nodrošinātu jums pakalpojumus
            pieejams, izmantojot Vietni, un lai jūs varētu izmantot dažus no tās
            Iespējas. Tie palīdz autentificēt lietotājus un novērst krāpniecisku
            izmantošanu lietotāju kontiem. Bez šīm sīkdatnēm jūsu sniegtie
            pakalpojumi pieprasīto nevar nodrošināt, un mēs izmantojam šīs
            sīkdatnes tikai, lai sniegt jums šos pakalpojumus.
          </p>
        </li>
        <li>
          <p>
            <strong>
              Sīkfailu politika / Paziņojums par sīkfailu pieņemšanu
            </strong>
          </p>
          <p>Veids: pastāvīgie sīkfaili</p> <p>Pārvalda: mēs</p>
          <p>
            Mērķis: Šīs sīkdatnes nosaka, vai lietotāji ir piekrituši izmantot
            sīkdatnes vietnē.
          </p>
        </li>
        <li>
          <p>
            <strong>Funkcionalitātes sīkfaili</strong>
          </p>
          <p>Veids: pastāvīgie sīkfaili</p> <p>Pārvalda: mēs</p>
          <p>
            Mērķis: šīs sīkdatnes ļauj mums atcerēties jūsu izdarītās izvēles,
            kad Jūs izmantojat vietni, piemēram, atceraties savus pieteikšanās
            datus vai valodas izvēle. Šo sīkfailu mērķis ir nodrošināt jums ar
            personiskāku pieredzi un lai izvairītos no atkārtotas ienākšanas
            jūsu preferences katru reizi, kad izmantojat vietni.
          </p>
        </li>
      </ul>
      <p>
        Lai iegūtu papildinformāciju par mūsu izmantotajām sīkdatnēm un jūsu
        izvēlēm sīkfailus, lūdzu, apmeklējiet mūsu sīkfailu politiku vai mūsu
        sīkfailu sadaļu Privātuma politika.
      </p>
      <strong className="text-2xl">Jūsu personas datu izmantošana</strong>
      <p>Uzņēmums var izmantot Personas datus šādiem mērķiem:</p>
      <ul>
        <li>
          <p>
            <strong>Lai nodrošinātu un uzturētu mūsu Pakalpojumu</strong>,
            tostarp uzraudzīt mūsu Pakalpojuma lietošanu.
          </p>
        </li>
        <li>
          <p>
            <strong>Lai pārvaldītu savu kontu:</strong> lai pārvaldītu jūsu
            reģistrāciju kā Pakalpojuma lietotājs. Jūsu sniegtie personas dati
            var jums sniegt piekļuvi dažādām Pakalpojuma funkcijām, kas ir
            pieejams Jums kā reģistrētam lietotājam.
          </p>
        </li>
        <li>
          <p>
            <strong>Līguma izpildei:</strong> izstrāde, pirkuma līguma
            ievērošana un izpilde jūsu iegādātajiem produktiem, precēm vai
            pakalpojumiem vai citiem līgumu ar Mums, izmantojot Pakalpojumu.
          </p>
        </li>
        <li>
          <p>
            <strong>Lai sazinātos ar jums:</strong> lai sazinātos ar jums pa
            e-pastu vai tālruni zvani, SMS vai citi līdzvērtīgi elektroniskās
            saziņas veidi, piemēram, mobilās lietojumprogrammas push paziņojumi
            par atjauninājumiem vai informatīva saziņa, kas saistīta ar
            funkcijām, produkti vai līgumpakalpojumi, tostarp drošības
            atjauninājumi, kad tas ir nepieciešams vai pamatoti to īstenošanai.
          </p>
        </li>
        <li>
          <p>
            <strong>Lai sniegtu jums</strong> jaunumus, īpašos piedāvājumus un
            vispārīga informācija par citām mūsu precēm, pakalpojumiem un
            pasākumiem piedāvājums, kas ir līdzīgs tiem, kurus jau esat
            iegādājies vai jautāja, ja vien neesat izvēlējies tādus nesaņemt
            informāciju.
          </p>
        </li>
        <li>
          <p>
            <strong>Lai pārvaldītu jūsu pieprasījumus:</strong> lai apmeklētu un
            pārvaldītu jūsu pieprasījumus pieprasījumus Mums.
          </p>
        </li>
        <li>
          <p>
            <strong>Uzņēmuma nodošanai:</strong> mēs varam izmantot jūsu
            informāciju novērtēt vai veikt apvienošanos, nodalīšanu,
            pārstrukturēšanu, reorganizāciju, likvidāciju vai citādu pārdošanu
            vai nodošanu dažu vai visiem mūsu aktīviem neatkarīgi no tā, vai tas
            ir nepārtraukts uzņēmums vai kā daļa no tā bankrota, likvidācijas
            vai līdzīga procedūra, kurā Person Mūsu rīcībā esošie dati par mūsu
            Pakalpojuma lietotājiem ir viens no aktīviem nodots.
          </p>
        </li>
        <li>
          <p>
            <strong>Citiem mērķiem</strong>: mēs varam izmantot jūsu informāciju
            citiem mērķiem, piemēram, datu analīzei, lietošanas tendenču
            noteikšanai, mūsu reklāmas kampaņu efektivitātes noteikšana un
            novērtēt un uzlabot mūsu Pakalpojumu, produktus, pakalpojumus,
            mārketingu un savu pieredzi.
          </p>
        </li>
      </ul>
      <p>Mēs varam kopīgot jūsu personas informāciju šādos gadījumos:</p>
      <ul>
        <li>
          <strong>Ar pakalpojumu sniedzējiem:</strong> mēs varam kopīgot jūsu
          personas datus informāciju ar pakalpojumu sniedzējiem, lai uzraudzītu
          un analizētu izmantošanu mūsu pakalpojumu, lai sazinātos ar jums.
        </li>
        <li>
          <strong>Uzņēmuma nodošanai:</strong> mēs varam koplietot vai nodot
          jūsu informāciju personas informācija saistībā ar sarunām vai sarunu
          laikā jebkura apvienošanās, Uzņēmuma aktīvu pārdošana, finansēšana vai
          visa iegāde vai mūsu uzņēmuma daļu citam uzņēmumam.
        </li>
        <li>
          <strong>Ar saistītajiem uzņēmumiem:</strong> mēs varam kopīgot jūsu
          informāciju ar Mūsu saistītie uzņēmumi, un tādā gadījumā mēs
          pieprasīsim to darīt šiem saistītajiem uzņēmumiem ievērot šo Privātuma
          politiku. Filiāles ietver Mūsu mātes uzņēmumu un jebkuri citi
          meitasuzņēmumi, kopuzņēmuma partneri vai citi uzņēmumi, kas Mēs
          kontrolējam vai kas ir kopīgā kontrolē ar mums.
        </li>
        <li>
          <strong>Ar biznesa partneriem:</strong> mēs varam kopīgot jūsu
          informāciju ar Mūsu biznesa partneriem, lai piedāvātu Jums noteiktus
          produktus, pakalpojumus vai akcijas.
        </li>
        <li>
          <strong>Ar citiem lietotājiem:</strong> kad kopīgojat personas
          informāciju vai citādi mijiedarboties publiskās vietās ar citiem
          lietotājiem, piemēram informāciju var skatīt visi lietotāji un to var
          izplatīt publiski ārpusē.
        </li>
        <li>
          <strong>Ar jūsu piekrišanu</strong>: mēs varam izpaust jūsu personas
          datus informāciju jebkuram citam nolūkam ar Jūsu piekrišanu.
        </li>
      </ul>
      <strong className="text-2xl">Jūsu personas datu saglabāšana</strong>
      <p>
        Uzņēmums saglabās Jūsu personas datus tikai tik ilgi, cik tas ir
        nepieciešami šajā Privātuma politikā noteiktajiem mērķiem. Mēs būsim
        saglabāt un izmantot Jūsu personas datus, ciktāl tas ir nepieciešams,
        lai tos ievērotu mūsu juridiskās saistības (piemēram, ja mums ir
        jāsaglabā jūsu datus, lai ievērotu piemērojamos tiesību aktus),
        atrisinātu strīdus un īstenotu mūsu juridiskos līgumus un politikas.
      </p>
      <p>
        Uzņēmums saglabās Lietošanas datus arī iekšējās analīzes vajadzībām.
        Lietošanas dati parasti tiek saglabāti īsāku laiku, izņemot kad šie dati
        tiek izmantoti drošības stiprināšanai vai uzlabošanai mūsu Pakalpojuma
        funkcionalitāti, vai arī mums ir juridisks pienākums to saglabāt datus
        par ilgākiem laika periodiem.
      </p>
      <strong className="text-2xl">Jūsu personas datu pārsūtīšana</strong>
      <p>
        Jūsu informācija, tostarp Personas dati, tiek apstrādāta uzņēmumā kas
        darbojas birojos un jebkurā citā vietā, kur iesaistītās puses apstrāde
        atrodas. Tas nozīmē, ka šī informācija var būt pārsūtīts uz datoriem,
        kas atrodas ārpus jūsu, un tiek uzturēti tajos štatā, provincē, valstī
        vai citā valdības jurisdikcijā, kur datu aizsardzības likumi var
        atšķirties no jūsu jurisdikcijas likumiem.
      </p>
      <p>
        Jūsu piekrišana šai Privātuma politikai, kam seko šādas informācijas
        iesniegšana informācija atspoguļo jūsu piekrišanu šai pārsūtīšanai.
      </p>
      <p>
        Uzņēmums veiks visus saprātīgi nepieciešamos pasākumus, lai nodrošinātu,
        ka Jūsu dati tiek apstrādāti droši un saskaņā ar šo Privātuma politiku
        un Jūsu Personas dati netiks nodoti organizācijai vai valstī, ja vien
        nav ieviesta atbilstoša kontrole, tostarp Jūsu datu un citas personiskās
        informācijas drošību.
      </p>
      <strong className="text-2xl">Izdzēsiet savus personas datus</strong>
      <p>
        Jums ir tiesības dzēst vai lūgt, lai Mēs palīdzam dzēst Personas dati,
        ko mēs esam apkopojuši par jums.
      </p>
      <p>
        Mūsu pakalpojums var dot jums iespēju dzēst noteiktu informāciju par Jūs
        no Pakalpojuma.
      </p>
      <p>
        Jūs jebkurā laikā varat atjaunināt, grozīt vai dzēst savu informāciju,
        parakstoties savā kontā, ja jums tāds ir, un apmeklējiet konta
        iestatījumus sadaļa, kas ļauj pārvaldīt savu personisko informāciju. Jūs
        varat arī sazinieties ar mums, lai pieprasītu piekļuvi, labotu vai
        dzēstu jebkuru personisku informāciju, ko esat mums sniedzis.
      </p>
      <p>
        Tomēr, lūdzu, ņemiet vērā, ka mums, iespējams, būs jāsaglabā noteikta
        informācija kad mums ir juridisks pienākums vai likumīgs pamats to
        darīt.
      </p>
      <strong className="text-2xl">Jūsu personas datu izpaušana</strong>
      <h3>Uzņēmējdarbības darījumi</h3>
      <p>
        Ja Uzņēmums ir iesaistīts apvienošanā, iegādē vai aktīvu pārdošanā, Jūsu
        Personas dati var tikt pārsūtīti. Mēs sniegsim paziņojumu pirms jūsu
        Personas dati tiek pārsūtīti, un uz tiem attiecas cita Privātuma
        politika Politika.
      </p>
      <h3>Tiesībaizsardzība</h3>
      <p>
        Noteiktos apstākļos Sabiedrībai var būt pienākums atklāt informāciju
        Jūsu personas dati, ja to pieprasa likums vai atbilde uz derīgu valsts
        iestāžu (piemēram, tiesas vai valsts aģentūras) pieprasījumi.
      </p>
      <h3>Citas juridiskās prasības</h3>
      <p>
        Uzņēmums var izpaust Jūsu Personas datus godprātīgi ka šāda darbība ir
        nepieciešama, lai:
      </p>
      <ul>
        <li>Ievērojiet juridisko pienākumu</li>
        <li>Aizsargājiet un aizstāviet Uzņēmuma tiesības vai īpašumu</li>
        <li>
          Novērst vai izmeklēt iespējamos pārkāpumus saistībā ar apkalpošana
        </li>
        <li>
          Aizsargājiet Pakalpojuma Lietotāju vai sabiedrības personīgo drošību
        </li>
        <li>Aizsargāt no juridiskās atbildības</li>
      </ul>
      <strong className="text-2xl">Jūsu personas datu drošība</strong>
      <p>
        Jūsu personas datu drošība mums ir svarīga, taču atcerieties to nekādas
        pārraides metodes internetā vai elektroniskās metodes glabāšana ir 100%
        droša. Lai gan mēs cenšamies izmantot komerciāli pieņemamu nozīmē
        aizsargāt Jūsu personas datus, mēs nevaram garantēt to absolūtu drošību.
      </p>
      <strong className="text-3xl">Bērnu konfidencialitāte</strong>
      <p>
        Mūsu pakalpojums neuzrunā nevienu, kas jaunāks par 13 gadiem. Mēs to
        nerunājam apzināti vākt personu identificējošu informāciju no jebkura
        zem 13 gadu vecumā. Ja esat vecāks vai aizbildnis un jūs to apzināties
        Jūsu bērns ir sniedzis mums personas datus, lūdzu, sazinieties ar mums.
        Ja mēs uzzināt, ka Mēs esam apkopojuši Personas datus no jebkura saskaņā
        ar 13 gadu vecumu bez vecāku piekrišanas pārbaudes, Mēs veicam
        pasākumus, lai noņemt šo informāciju no Mūsu serveriem.{" "}
      </p>
      <p>
        Ja mums ir jāpaļaujas uz piekrišanu kā juridisko pamatu Jūsu apstrādei
        informāciju un Jūsu valstī ir nepieciešama vecāku piekrišana, Mēs varam
        pirms Mēs to ievācam un izmantojam, nepieciešama jūsu vecāku piekrišana
        informāciju.
      </p>
      <strong className="text-3xl">Saites uz citām vietnēm</strong>
      <p>
        Mūsu Pakalpojumā var būt saites uz citām vietnēm, kuras nepārvalda Mēs.
        Ja noklikšķināsit uz trešās puses saites, jūs tiksit novirzīts uz to
        trešās puses vietne. Mēs ļoti iesakām jums pārskatīt Privātuma politiku
        no katras apmeklētās vietnes.
      </p>
      <p>
        Mēs nekontrolējam un neuzņemamies atbildību par saturu, trešo pušu
        vietņu vai pakalpojumu privātuma politikas vai prakse.
      </p>
      <strong className="text-3xl">
        Šīs konfidencialitātes politikas izmaiņas
      </strong>
      <p>
        Mēs varam laiku pa laikam atjaunināt savu privātuma politiku. Mēs jums
        paziņosim par jebkādām izmaiņām, šajā lapā ievietojot jauno Privātuma
        politiku.
      </p>
      <p>
        Mēs jūs informēsim pa e-pastu un/vai pamanāmu paziņojumu mūsu
        pakalpojumā, pirms izmaiņu stāšanās spēkā un atjauniniet &quot;Pēdējais
        atjaunināts&quot; datumu šīs Privātuma politikas augšpusē.
      </p>
      <p>
        Jums ir ieteicams periodiski pārskatīt šo Privātuma politiku attiecībā
        uz jebkuru izmaiņas. Izmaiņas šajā Privātuma politikā ir spēkā, kad tās
        ir spēkā ievietots šajā lapā.
      </p>
      <strong className="text-3xl">Sazinieties ar mums</strong>
      <p>
        Ja jums ir kādi jautājumi par šo Privātuma politiku, varat sazināties ar
        mums:
      </p>
      <ul>
        <li>
          <p>Pa e-pastu: info@quickstack.lv</p>
        </li>
        <li>
          <p>Pa tālruņa numuru: 26956611</p>
        </li>
      </ul>
    </section>
  );
};

export default PrivacyPolicy;
